name: Build, Test, and Code Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      # Restore dependencies
      - name: Restore Dependencies
        run: dotnet restore

      # Build the project
      - name: Build
        run: dotnet build --no-restore --configuration Release

      # Run tests with coverage using a custom runsettings file
      - name: Test with Coverage
        run: dotnet test --no-build --configuration Release --settings coverlet.runsettings

      # Debugging step to find coverage files
      - name: Debug Coverage Files
        run: find . -name "coverage.cobertura.xml"

      # Install ReportGenerator
      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      # Convert coverage report to HTML
      - name: Convert Coverage Report
        env:
          PATH: $PATH:/home/runner/.dotnet/tools
        run: |
          reportgenerator \
          -reports:**/TestResults/**/coverage.cobertura.xml \
          -targetdir:coverage-report \
          -reporttypes:Html

      # Upload coverage report artifact
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage-report

      # Upload raw coverage data for debugging purposes (optional)
      - name: Upload Raw Coverage Data
        uses: actions/upload-artifact@v3
        with:
          name: raw-coverage-data
          path: "**/TestResults/"
