name: Build and Test C# Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0' # Use the required version of .NET SDK

      # Restore dependencies
      - name: Restore Dependencies
        run: dotnet restore

      # Build the project
      - name: Build
        run: dotnet build --no-restore --configuration Release

      # Run tests
      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal
